# Generated by Django 4.2.1 on 2023-05-30 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestToBeBlogger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('bio', models.TextField(help_text='tell us a little about yourself', max_length=2000)),
                ('request_date', models.DateTimeField()),
                ('status', models.CharField(blank=True, choices=[('A', 'Accepted'), ('P', 'Pending'), ('R', 'Rejected')], default='P', help_text='status of your request', max_length=1)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['request_date'],
            },
        ),
    ]
