# Generated by Django 4.2.1 on 2023-05-30 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_requesttobeblogger'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requesttobeblogger',
            options={'ordering': ['request_date'], 'permissions': (('can_approve_request', 'set user as blogger'),)},
        ),
    ]
