# Generated by Django 4.2.1 on 2023-05-31 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_requesttobeblogger_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['name', 'blogger'], 'permissions': (('can_approve_request', 'set user as blogger'),)},
        ),
    ]
